engines:
    coffeelint:
        enabled: true
        checks:
            indentation:
                enabled: false
            no_tabs:
                enabled: false
    fixme:
        enabled: true
ratings:
    paths:
    - "**.coffee"
exclude_paths: []
